[[redirects]]
  from = "/blog/89ff4b7d-152d-4806-a05d-29b52d2d58a8"
  to = "/blog/prologue"
  status = 301
  force = false
  query = {path = ":path"}


[[redirects]]
  from = "/blog/8a7c8d41-c950-4074-8514-3d5d3afc78a2"
  to = "/blog/manto-film-review"
  status = 301
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/blog/44320b9c-c5cd-4593-a4ed-3d4727c839af"
  to = "/blog/alexander-the-great-and-the-fountain-of-youth"
  status = 301
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/tribunals/4e9a07c2-b811-4d72-985b-5fab0e73ff4c"
  to = "/blog/jagjit-singh-the-ghazal-maestro"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/4f85c557-f990-4a4a-a56a-9f6de631efd4"
  to = "/blog/thank-you"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/tribunals/f16099f1-f23e-4bfa-b6f7-86a2ad4b8434"
  to = "/blog/tabu-a-timeless-artist"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/tribunals/3840bb03-1301-4b90-9373-32f686d708c9"
  to = "/blog/allama-iqbal-distinguished-philosopher-failed-politician"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/tribunals/df14f1b8-2ed5-41db-8308-00a9f314eb14"
  to = "/blog/stan-marvellous-lee"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/the-political-dilemma-of-rajasthan"
  to = "/blog/cc176bf3-4428-4684-9470-dbef9d0a56e0"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/798a0d47-50e0-48a9-8633-dc77c456d9c4"
  to = "/blog/uri-the-surgical-strike-movie-review"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/tribunals/62cfd5af-766c-4e97-89d0-c751cab96eb3"
  to = "/blog/bob-marley-in-rajasthan"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/74384b28-0ee8-4756-900d-c0eab7ff727b"
  to = "/blog/war-between-keyboard-warriors"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/4bcdb591-42fa-445e-8fec-92faac943260"
  to = "/blog/kesari-movie-review"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/c255f939-b90b-4b79-8213-f2ff31d1b8c7"
  to = "/blog/things-not-to-do-in-arunachal-pradesh"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/ad229199-15d8-4ca6-8b1e-c84ac4b03039"
  to = "/blog/current-economic-slowdown-is-just-a-teaser-the-show-is-about-to-appear"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/why-indian-media-are-not-showing-what-international-media-are-showing-about-kashmir"
  to = "/blog/a0e285f8-f436-466f-b41c-472f4cd9c581"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/88a46e09-71c1-41d7-ae76-d94a7f6bd7d1"
  to = "/blog/subramanian-swamy-swami-of-own"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/4c50c54f-8c19-4def-a2c2-5a2be85ee18f"
  to = "/blog/backpacking-in-arunachal-pradesh-part-1"
  status = 301
  force = false
  query = {path = ":path"}
[[redirects]]
  from = "/blog/cc6523de-c989-440d-ae69-15b79619c657"
  to = "/blog/integer-to-words-converter-in-laravel"
  status = 301
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
