backend:
  name: git-gateway
  branch: develop

media_folder: static/blogs
public_folder: blogs

collections:
- name: blog
  label: Blog
  folder: "content/blog"
  create: true
  fields:
  - { label: 'template', name: 'template', widget: 'hidden', default: 'blog' }
  - label: 'Master Category'
    name: 'master_category'
    widget: 'select'
    options:
    - { label: 'Arunachal Pradesh', value: 'Arunachal Pradesh' }
    - { label: 'Books', value: 'Books' }
    - { label: 'Culture', value: 'Culture' }
    - { label: 'Economics', value: 'Economics' }
    - { label: 'Events', value: 'Events' }
    - { label: 'History', value: 'History' }
    - { label: 'Life', value: 'Life' }
    - { label: 'Movies', value: 'Movies' }
    - { label: 'Politics', value: 'Politics' }
    - { label: 'Programming', value: 'Programming' }
    - { label: 'Tribute', value: 'Tribute' }
    - { label: 'Travel', value: 'Travel' }
  - { name: featuredImage, label: Featured Image, widget: image }
  - { name: fullBanner, label: Full Banner, widget: boolean, default: true }
  - { name: seoTitle, label: Seo Title }
  - { name: title, label: Title }
  - { name: slug, label: Blog Slug, default: '/blog/' }
  - { name: draft, label: Draft, widget: boolean, default: true }
  - { name: date, label: Publish Date, widget: datetime }
  - { name: dateModified, label: Modified Date, widget: datetime }
  - { name: keywords, label: Keywords }
  - {
    label: 'Tags',
    name: 'tags',
    widget: 'list',
  }
  - { name: description, label: description, widget: 'text' }
  - { name: body, label: Body, widget: markdown }

